# ===========================================================
# 网站基本信息配置
# ===========================================================

# 基础基础信息
site:
  title: 小梦岛
  subtitle: Live a Vidorra Life
  description: 当你可以跟一个人不说话，分享片刻寂静，且不会觉得尴尬，那一刻你就会明白，你遇到了对的人。

# 右侧书签分类设置
categories:
  limit: 6

# Open graph meta tags
# https://developers.facebook.com/docs/sharing/webmasters/
open_graph_meta:
  enable: true
  option:
   twitter_card: '123'
   twitter_image: '123'
   twitter_id: '123'
   twitter_site: '123'
   google_plus: '123'
   fb_admins: '123'
   fb_app_id: '123'

# Avatar (頭像)
avatar: /images/royians/avatar.jpg

# Favicon（網站圖標）
favicon: /images/royians/logo.png

site_verification:
 - name: google-site-verification
   content: xxxxxx
 - name: baidu-site-verification
   content: xxxxxxx

# PWA
# See https://github.com/JLHwung/hexo-offline
pwa:
  enable: false
  manifest: /pwa/manifest.json
  apple_touch_icon: /pwa/apple-touch-icon.png
  favicon_32_32: /pwa/32.png
  favicon_16_16: /pwa/16.png
  mask_icon: /pwa/safari-pinned-tab.svg

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
 head:
#  - <link rel="stylesheet" href="/xxx.css">
 bottom:
#  - <script src="xxxx"></script>

# A simple 404 page
error_404:
  enable: true
  subtitle: 'Page Not Found'
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.png

# Time difference between publish date and now (網頁運行時間)
# Formal: Month/Day/Year Time or Year/Month/Day Time
runtimeshow:
 enable: false
 publish_date:

# figcaption (圖片描述文字)
photofigcaption: false

# show scroll percent in scroll-to-top button
rightside_scroll_percent: false

# ===========================================================
# 网站样式配置
# ===========================================================

# Default display mode (网站默认样式)
# light (default) / dark
display_mode: light

# dark mode
darkmode:
 enable: true
 # Toggle Button to switch dark/light mode
 button: true
 # Switch dark/light mode automatically (自動切換 dark mode和 light mode)
 # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
 # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
 # autoChangeMode: false
 autoChangeMode: false

# Global font settings
# Don't modify the following settings unless you know how they work (非必要不要修改)
font:
 global-font-size:
 code-font-size:
 font-family:
 code-font-family:

# Font settings for the site title and site subtitle
# 左上角網站名字 主頁居中網站名字
blog_title_font:
  font_link:
  font-family:

# 主题色
theme_color:
  main: "#009688"
  paginator: "#00c4b6"
  button_hover: "#FF7242"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"
  scrollbar_color: "#49b1f5"
  meta_theme_color_light: "ffffff"
  meta_theme_color_dark: "#0d0d0d"

# Website Background (設置網站背景)
# can set it to color or image (可設置圖片 或者 顔色)
# The formal of image: url(http://xxxxxx.com/xxx.jpg)
background: "#009688"

# https://github.com/vinta/pangu.js
# Insert a space between Chinese character and English character (中英文之間添加空格)
pangu:
 enable: false
 field: site # site/post

# anchor
anchor:
 button:
  enable: false
  always_show: false
  icon: # the unicode value of Font Awesome icon, such as '\3423'
 auto_update: false # when you scroll in post, the URL will update according to header id.

# toc (目錄)
toc:
 post: true
 page: false
 number: true
 expand: false
 style_simple: false # for post
 scroll_percent: true

# ===========================================================
# 网站功能配置
# ===========================================================

# https://instant.page/
# prefetch (預加載)
instantpage: false

# Code Blocks (代碼相關)
# --------------------------------------

highlight_theme: light #  darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # copy button
highlight_lang: true # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
highlight_height_limit: false # unit: px
code_word_wrap: false

# Inject the css and script (aplayer/meting)
aplayerInject:
 enable: false
 per_page: true

# Conversion between Traditional and Simplified Chinese (簡繁轉換)
translate:
 enable: true
 # The text of a button
 default: 繁
 # the language of website (1 - Traditional Chinese/ 2 - Simplified Chinese）
 defaultEncoding: 2
 # Time delay
 translateDelay: 0
 # The text of the button when the language is Simplified Chinese
 msgToTraditionalChinese: '繁'
 # The text of the button when the language is Traditional Chinese
 msgToSimplifiedChinese: '簡'

# Lazyload (圖片懶加載)
# https://github.com/verlok/vanilla-lazyload
lazyload:
 enable: false
 field: site # site/post
 placeholder:
 blur: false

# mermaid
# see https://github.com/mermaid-js/mermaid
mermaid:
 enable: false
 # built-in themes: default/forest/dark/neutral
 theme:
  light: default
  dark: dark

# Pjax
# It may contain bugs and unstable, give feedback when you find the bugs.
# https://github.com/MoOx/pjax
pjax:
 enable: false
 exclude:
 # - xxxx
 # - xxxx

# Algolia search
algolia_search:
 enable: false
 hits:
  per_page: 6

# Local search
local_search:
 enable: false
 preload: false
 CDN:

# Docsearch
# https://docsearch.algolia.com/
docsearch:
 enable: false
 appId:
 apiKey:
 indexName:
 option:

# copy settings
# copyright: Add the copyright information after copied content (複製的內容後面加上版權信息)
copy:
 enable: true
 copyright:
  enable: false
  limit_count: 50

post_meta:
 page: # Home Page
  date_type: created # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
  date_format: date # date/relative 顯示日期還是相對日期
  categories: true # true or false 主頁是否顯示分類
  tags: false # true or false 主頁是否顯示標籤
  label: true # true or false 顯示描述性文字
 post:
  date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
  date_format: date # date/relative 顯示日期還是相對日期
  categories: true # true or false 文章頁是否顯示分類
  tags: true # true or false 文章頁是否顯示標籤
  label: true # true or false 顯示描述性文字

# busuanzi count for PV / UV in site
# 訪問人數
busuanzi:
 site_uv: true
 site_pv: true
 page_pv: true

# ===========================================================
# 网站分析统计插件
# ===========================================================

# Google Analytics
# https://analytics.google.com/analytics/web/
google_analytics:

# Baidu Analytics
# https://tongji.baidu.com/web/welcome/login
baidu_analytics:

# Cloudflare Analytics
# https://www.cloudflare.com/zh-tw/web-analytics/
cloudflare_analytics:

# Microsoft Clarity
# https://clarity.microsoft.com/
microsoft_clarity:

# ===========================================================
# 广告
# ===========================================================

# Google Adsense (谷歌廣告)
google_adsense:
 enable: false
 auto_ads: true
 js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
 client:
 enable_page_level_ads: true

# ===========================================================
# CDN配置
# ===========================================================

# CDN
# Don't modify the following settings unless you know how they work
# 非必要請不要修改
CDN:
 # The CDN provider of internal scripts (主題內部 js 的 cdn 配置)
 # option: local/jsdelivr/unpkg/cdnjs/custom
 # Dev version can only choose. ( dev版的主題只能設置為 local )
 internal_provider: local

 # The CDN provider of third party scripts (第三方 js 的 cdn 配置)
 # option: jsdelivr/unpkg/cdnjs/custom
 third_party_provider: jsdelivr

 # Add version number to url, true or false
 version: true

 # Custom format
 # For example: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
 custom_format:

 option:
 # main_css:
 # main:
 # utils:
 # translate:
 # local_search:
 # algolia_js:
 # algolia_search:
 # instantsearch:
 # docsearch_js:
 # docsearch_css:
 # pjax:
 # gitalk:
 # gitalk_css:
 # blueimp_md5:
 # valine:
 # disqusjs:
 # disqusjs_css:
 # twikoo:
 # waline_js:
 # waline_css:
 # sharejs:
 # sharejs_css:
 # mathjax:
 # katex:
 # katex_copytex:
 # mermaid:
 # canvas_ribbon:
 # canvas_fluttering_ribbon:
 # canvas_nest:
 # lazyload:
 # instantpage:
 # typed:
 # pangu:
 # fancybox_css:
 # fancybox:
 # medium_zoom:
 # activate_power_mode:
 # fireworks:
 # click_heart:
 # ClickShowText:
 # fontawesome:
 # flickr_justified_gallery_js:
 # flickr_justified_gallery_css:
 # aplayer_css:
 # aplayer_js:
 # meting_js:
 # prismjs_js:
 # prismjs_lineNumber_js:
 # prismjs_autoloader:
 # artalk_js:
 # artalk_css:
 # busuanzi:
